### ISSUE TITLE
sections are getting auto-created

### ISSUE THREAD

**Issue by jtauber** [pinax/pinax-project-blog#4]
I haven't looked where it's coming from, but sections from Pinax's blog are getting auto-created and I don't think they should be here. Perhaps we should just auto-create a single "general" section or something.

**Comment by paltman** [comment]
I don't see how this is possible. There is a migration in `pinax-blog` that [auto-creates sections once](https://github.com/pinax/pinax-blog/blob/master/pinax/blog/migrations/0003_auto_20150529_0405.py#L11) but it's based on a setting that doesn't exist in this project.

**Comment by jtauber** [comment]
Ah, my project had the settings. That must be the root cause.
