### ISSUE TITLE
reconsider twitter link for authors

### ISSUE THREAD

**Issue by jtauber** [pinax/pinax-project-blog#5]
At the moment the default templates link the author of a post to their twitter page, assuming their twitter handle is the same as their username. This is a dangerous assumption and I'm wondering if the link should just be removed.

I can imagine wanting to link to an "About Me" page instead. 

It's an easy work around but this starter project should have the best possible default.

**Comment by jtauber** [comment]
fixed in 63bca4551dc064ecfa45e41390e5fd00b5ad0051

**Comment by paltman** [comment]
This was already fixed the other day in 63bca4551dc064ecfa45e41390e5fd00b5ad0051

**Comment by paltman** [comment]
BOOM
